# Generated by Django 4.2.3 on 2025-01-31 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('reg_date', models.DateField(help_text='The date of Company incoparation')),
                ('directors', models.TextField(help_text='List of directors, separated by commas')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_issuer', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('registration_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('validity_period', models.CharField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='upload.company')),
            ],
        ),
    ]
