# Generated by Django 4.2.3 on 2025-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='document type name', max_length=100, unique=True)),
                ('document_issuer', models.CharField(help_text='The Authority issuing the document', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_issuer',
        ),
    ]
